# Generated by Django 4.0.3 on 2022-04-02 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
