# Generated by Django 4.0.3 on 2022-04-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220402_0935'),
        ('movies', '0004_actor_movie_actors'),
    ]

    operations = [
    ]
