# Generated by Django 4.0.3 on 2022-04-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220403_1123'),
        ('movies', '0005_merge_0003_auto_20220402_0935_0004_actor_movie_actors'),
    ]

    operations = [
    ]
