# Generated by Django 4.0.3 on 2022-04-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_likes'),
        ('movies', '0006_merge_20220403_1326'),
    ]

    operations = [
    ]
