# Generated by Django 4.0.3 on 2022-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_merge_0005_movie_likes_0006_merge_20220403_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('contact_at', models.DateField()),
            ],
        ),
    ]
