# Generated by Django 4.0.3 on 2022-04-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_contact'),
        ('movies', '0008_contact'),
    ]

    operations = [
    ]
