# Generated by Django 4.0.3 on 2022-04-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_director'),
        ('movies', '0010_alter_movie_director'),
    ]

    operations = [
    ]
